### PR TITLE
I270 install on device banner UI update

### LINKED ISSUE #270: Install on device banner UI update
## Basic Information
make pretty

### PR DESCRIPTION
**Pull request by ChantelleKerr**
## Change Summary

**[Briefly summarise the changes that you made. Just high-level stuff]**
- Updated UI on banner to install as PWA

### Change Form

**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information

**[Is there anything in particular in the review that I should be aware of?]**

# Related Issue

- Resolve #270

### CODE REVIEW

**Comment by RadioArsenic** [comment]
Tried laptop, phone, and ipad and clearing all sorts of data, still haven't gotten install button to show up. Do think it's a me problem though

**Comment by HuxleyBerry** [comment]
FWIW, the install button is present and works for me

**Comment by ChantelleKerr** [comment]
It works for Jack, Dylan, Danish, James and Nick. I think its good to merge

**Review by RadioArsenic — APPROVED** [review]
That's good enough for me

**Pull request merged**
